listen: :443

tls:
  cert: "certpath"
  key: "keypath"

auth:
  type: userpass
  userpass:
    testuser1: testpassword1

ignoreClientBandwidth: false

quic:
  initStreamReceiveWindow: 26843545
  maxStreamReceiveWindow: 26843545
  initConnReceiveWindow: 67108864
  maxConnReceiveWindow: 67108864

masquerade: 
  type: proxy
  proxy:
    url: https://genshin.hoyoverse.com/
    rewriteHost: true
